import { NextRequest } from "next/server";
import crypto from "crypto";
import { CDN_DOWNLOAD_BASE, CDN_STREAM_BASE } from "@/lib/constants";

// Streaming a multi-hundred-MB response through Edge runtime is unsafe
// (memory + duration limits). Force nodejs.
export const runtime = "nodejs";
// Don't let Next try to cache or pre-render this.
export const dynamic = "force-dynamic";

/**
 * GET /api/download/file
 *
 * Streams a file from the CDN back to the browser with
 * `Content-Disposition: attachment` so it actually downloads, instead
 * of being played inline (pushr.io's S3 implementation forces stored
 * Content-Disposition: inline; filename="<key>" on every object,
 * regardless of what we set via mc --attr — so we can't fix this at
 * the CDN. Injecting the right header here is the only viable path).
 *
 * Required query params (generated by /api/download after auth+quota):
 *   url   — the CDN URL to proxy (must start with an allowed CDN base)
 *   exp   — millisecond unix timestamp after which this signed URL is invalid
 *   sig   — HMAC-SHA256 of `${url}|${exp}` using IP_HASH_SALT
 *
 * Forwards the client's Range header so multi-GB downloads can resume.
 */

function getAllowedCdnBases(): string[] {
  const bases: string[] = [];
  if (CDN_DOWNLOAD_BASE) bases.push(CDN_DOWNLOAD_BASE);
  if (CDN_STREAM_BASE) bases.push(CDN_STREAM_BASE);
  return bases;
}

function verifySig(url: string, exp: string, sig: string): boolean {
  const secret = process.env.IP_HASH_SALT || "";
  if (!secret) return false;
  const expected = crypto
    .createHmac("sha256", secret)
    .update(`${url}|${exp}`)
    .digest("hex");
  // Timing-safe compare — sig and expected are same-length hex strings.
  if (sig.length !== expected.length) return false;
  return crypto.timingSafeEqual(Buffer.from(sig), Buffer.from(expected));
}

/**
 * Build a sensible download filename from the CDN URL.
 *   Input  : https://cdn.example.com/Series%20-%2001/1080p_full.mkv
 *   Output : Series - 01 - 1080p.mkv
 * Sanitized to ASCII-safe chars for the Content-Disposition value.
 */
function deriveFilename(url: string): string {
  const decoded = decodeURIComponent(url);
  const parts = decoded.split("/");
  const file = parts[parts.length - 1] || "download.mkv"; // 1080p_full.mkv
  const folder = parts[parts.length - 2] || "";            // Series - 01
  // Extract quality from filename like "1080p_full.mkv" or "2160p_full.mkv"
  const qMatch = file.match(/(\d{3,4}p)/);
  const quality = qMatch ? qMatch[1] : "";
  // Strip extension to rebuild
  const ext = file.endsWith(".mkv") ? ".mkv" : `.${file.split(".").pop() || "mkv"}`;
  const base = quality ? `${folder} - ${quality}` : folder || file.replace(ext, "");
  // Content-Disposition filename: stick to ASCII-safe chars to avoid
  // browser quirks. Remove anything not in [\w. -].
  const safe = `${base}${ext}`.replace(/[^\w. -]/g, "_");
  return safe || "download.mkv";
}

export async function GET(request: NextRequest) {
  const url = request.nextUrl.searchParams.get("url");
  const exp = request.nextUrl.searchParams.get("exp");
  const sig = request.nextUrl.searchParams.get("sig");

  if (!url || !exp || !sig) {
    return new Response("Missing params", { status: 400 });
  }

  const expiresMs = parseInt(exp, 10);
  if (!Number.isFinite(expiresMs) || Date.now() > expiresMs) {
    return new Response("Signed URL expired", { status: 403 });
  }

  // URL allowlist check.
  const allowed = getAllowedCdnBases();
  if (!allowed.some((base) => url.startsWith(base + "/"))) {
    return new Response("Invalid CDN URL", { status: 400 });
  }

  if (!verifySig(url, exp, sig)) {
    return new Response("Invalid signature", { status: 403 });
  }

  // Forward Range header so download managers / resume-on-disconnect
  // both work. pushr.io respects Range on these objects.
  const range = request.headers.get("range");
  const upstreamHeaders: Record<string, string> = {
    Referer: "https://hentaiclick.tv/",
  };
  if (range) upstreamHeaders["Range"] = range;

  let upstream: Response;
  try {
    upstream = await fetch(url, { headers: upstreamHeaders });
  } catch (err) {
    console.error("[download/file] upstream fetch failed:", err);
    return new Response("CDN fetch failed", { status: 502 });
  }

  if (!upstream.ok && upstream.status !== 206) {
    return new Response(`CDN returned ${upstream.status}`, {
      status: 502,
    });
  }

  const filename = deriveFilename(url);

  // Force download semantics + filename. application/octet-stream
  // prevents any browser from second-guessing and trying to render
  // the file (which is the whole reason we built this proxy — the
  // CDN serves video/x-matroska + inline, so the browser tries to
  // play it).
  const responseHeaders: Record<string, string> = {
    "Content-Type": "application/octet-stream",
    "Content-Disposition": `attachment; filename="${filename}"`,
    "Accept-Ranges": "bytes",
    // Don't cache the proxied bytes at the browser level — every
    // download generates a fresh signed URL anyway, and we don't want
    // an old expired signature serving stale bytes.
    "Cache-Control": "private, no-store",
  };

  const cl = upstream.headers.get("content-length");
  if (cl) responseHeaders["Content-Length"] = cl;

  const cr = upstream.headers.get("content-range");
  if (cr) responseHeaders["Content-Range"] = cr;

  return new Response(upstream.body, {
    status: upstream.status, // 200 OR 206 partial-content
    headers: responseHeaders,
  });
}
